const app=document.querySelector('#app'),toastEl=document.querySelector('#toast');
const STORE='mnm-voice-pwa-v1';
const seed=[
 {id:'vale1',nome:'Vale do Sol 1',endereco:'Volta Redonda · RJ',registros:[
  {id:'r1',tipo:'Diário de obra',status:'quarentena',duracao:34,data:'Hoje, 14:32',transcricao:'Hoje concluímos a concretagem da laje do segundo pavimento. Equipe completa e sem ocorrências.',campos:[['Etapa','Estrutura'],['Serviço','Concretagem da laje'],['Equipe','12 profissionais'],['Observação','Serviço concluído sem ocorrências']]},
  {id:'r2',tipo:'Pedido de compra',status:'aprovado',duracao:28,data:'Ontem, 17:18',aprovacao:'Hoje, 08:15',transcricao:'Precisamos de cinquenta sacos de cimento CP dois para terça-feira.',campos:[['Material','Cimento CP II'],['Quantidade','50 sacos'],['Prazo','Terça-feira'],['Prioridade','Alta']]}
 ]},
 {id:'vale2',nome:'Vale do Sol 2',endereco:'Barra Mansa · RJ',registros:[{id:'r3',tipo:'Ocorrência',status:'rejeitado',duracao:19,data:'24 jul, 09:10',motivo:'Registro duplicado.',transcricao:'Chuva forte interrompeu a terraplanagem pela manhã.',campos:[['Categoria','Clima'],['Impacto','Atividade interrompida'],['Etapa','Terraplanagem']]}]},
 {id:'casa',nome:'Casa Fabiola & Julio',endereco:'Resende · RJ',registros:[]}
];
let state={screen:'home',obraId:null,registroId:null,recording:false,seconds:0,draft:null,playing:false,play:0,obras:load()};
let recorder=null,chunks=[],recordTimer=null,playTimer=null,audioBlob=null;
function load(){try{return JSON.parse(localStorage.getItem(STORE))||seed}catch{return seed}}
function save(){localStorage.setItem(STORE,JSON.stringify(state.obras))}
function obra(){return state.obras.find(o=>o.id===state.obraId)}
function registro(){return obra()?.registros.find(r=>r.id===state.registroId)}
function fmt(sec){return `${String(Math.floor(sec/60)).padStart(2,'0')}:${String(sec%60).padStart(2,'0')}`}
function esc(s=''){return String(s).replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]))}
function tags(r){const type={'Diário de obra':'tag-green','Pedido de compra':'tag-accent','Consumo de materiais':'tag-neutral','Ocorrência':'tag-outline'}[r.tipo]||'tag-neutral';const label={quarentena:'Em quarentena',aprovado:'Aprovado',rejeitado:'Rejeitado'}[r.status];const status=r.status==='aprovado'?'tag-green':r.status==='quarentena'?'tag-accent':'tag-neutral';return `<span class="tag ${type}">${r.tipo}</span><span class="tag ${status}">${label}</span>`}
function wave(n=14){return Array.from({length:n},(_,i)=>`<i style="height:${7+(i*17%18)}px;--delay:${(i%8)*.07}s"></i>`).join('')}
function toast(msg){toastEl.textContent=msg;toastEl.hidden=false;clearTimeout(toastEl._t);toastEl._t=setTimeout(()=>toastEl.hidden=true,2800)}
function go(screen){clearInterval(playTimer);state.playing=false;state.play=0;state.screen=screen;render()}
function header(title,sub,back=true){return `<header class="header bordered"><div class="header-row">${back?'<button class="icon-btn" data-action="back" aria-label="Voltar">‹</button>':''}<div class="header-copy"><h2>${esc(title)}</h2>${sub?`<p>${esc(sub)}</p>`:''}</div></div></header>`}
function home(){return `<section class="screen"><header class="header home-header"><img class="app-logo" src="assets/logo-mnm.png" alt="Mão na Massa"><div class="kicker">Módulo de voz</div><h1>Obras</h1><p>Toque em uma obra para ver os registros de voz</p>${navigator.onLine?'':'<span class="offline">OFFLINE</span>'}</header><main class="content stack">${state.obras.map(o=>{const p=o.registros.filter(r=>r.status==='quarentena').length;return `<button class="card" data-obra="${o.id}"><div class="card-title">${esc(o.nome)}</div><div class="card-body">${esc(o.endereco)}</div><div class="meta"><span>${o.registros.length} ${o.registros.length===1?'registro':'registros'}</span>${p?`<span class="tag tag-accent">${p} ${p===1?'pendente':'pendentes'}</span>`:''}</div></button>`}).join('')}</main></section>`}
function obraView(){const o=obra();return `<section class="screen">${header(o.nome,o.endereco)}<main class="content stack">${o.registros.length?o.registros.map(r=>`<div class="record-row"><article class="card record-card" data-registro="${r.id}" tabindex="0"><div class="audio-line"><span class="play-mini">▶</span><span class="wave">${wave()}</span><span class="duration">${fmt(r.duracao)}</span></div><div class="meta">${tags(r)}</div><div class="timestamp">${r.data}</div></article></div>`).join(''):'<div class="empty">Nenhum registro ainda.<br>Use o microfone para começar.</div>'}</main><footer class="bottom-bar"><div class="bottom-hint">Toque no microfone para gravar um novo registro</div><button class="record-btn" data-action="record" aria-label="Gravar">●</button></footer></section>`}
function recording(){return `<section class="screen">${header('Registro de voz','',true)}<main class="recording-body"><div class="kicker">Registro de voz</div><button class="record-orb ${state.recording?'active':''}" data-action="toggle-record" aria-label="${state.recording?'Parar e processar':'Começar a gravar'}">${state.recording?'■':'●'}</button><div class="timer">${fmt(state.seconds)}</div><div class="live-wave ${state.recording?'active':''}">${wave(20)}</div><p class="helper">${state.recording?'Toque para enviar':'Toque para começar a gravar'}</p></main></section>`}
function processing(){return `<section class="screen"><main class="processing"><div class="spinner"></div><h2 id="stageText">Transcrevendo áudio…</h2><p>Estamos organizando seu registro.</p></main></section>`}
function review(){const d=state.draft;return `<section class="screen">${header('Revisar lançamento','Confira antes de enviar')}<main class="content review"><div class="meta" style="margin:0 0 13px"><span class="tag tag-accent">${d.tipo}</span></div><article class="card section-card"><h3>O que você disse</h3><p class="transcript">“${esc(d.transcricao)}”</p></article><article class="card section-card"><h3>Dados extraídos</h3>${d.campos.map((c,i)=>`<div class="field"><label for="field${i}">${esc(c[0])}</label><input id="field${i}" data-field="${i}" value="${esc(c[1])}"></div>`).join('')}</article><div class="notice"><b>◷</b><span>O envio ficará em quarentena até a aprovação de um gestor.</span></div></main><footer class="review-actions"><button class="btn btn-ghost" data-action="discard">Descartar</button><button class="btn btn-primary" data-action="submit">Enviar para aprovação</button></footer></section>`}
function detail(){const r=registro(),notice=r.status==='quarentena'?['','◷','Em quarentena — aguardando a aprovação de um gestor antes de entrar no sistema.']:r.status==='aprovado'?['green','✓',`Aprovado e lançado no Mão na Massa em ${r.aprovacao}.`]:['neutral','×',`Rejeitado pelo gestor. Motivo: ${r.motivo}`];return `<section class="screen">${header(r.tipo,'Detalhe do registro')}<main class="content"><div class="meta" style="justify-content:space-between;margin:0 0 14px"><span>${tags(r)}</span><span>${r.data}</span></div><div class="notice ${notice[0]}"><b>${notice[1]}</b><span>${notice[2]}</span></div><article class="card section-card" style="margin-top:13px"><div class="player"><button data-action="play">${state.playing?'Ⅱ':'▶'}</button><div class="progress"><span style="width:${state.play}%"></span></div><span class="duration">${fmt(r.duracao)}</span></div></article><article class="card section-card"><h3>Transcrição</h3><p class="transcript">“${esc(r.transcricao)}”</p></article><article class="card section-card"><h3>Dados extraídos</h3>${r.campos.map(c=>`<div class="data-row"><small>${esc(c[0])}</small><strong>${esc(c[1])}</strong></div>`).join('')}</article></main></section>`}
function render(){app.innerHTML=({home,obra:obraView,recording,processing,review,detail}[state.screen]||home)();bind()}
function bind(){document.querySelectorAll('[data-obra]').forEach(el=>el.onclick=()=>{state.obraId=el.dataset.obra;go('obra')});document.querySelectorAll('[data-registro]').forEach(el=>el.onclick=()=>{state.registroId=el.dataset.registro;go('detail')});document.querySelectorAll('[data-action]').forEach(el=>el.onclick=()=>action(el.dataset.action));document.querySelectorAll('[data-field]').forEach(el=>el.oninput=()=>state.draft.campos[+el.dataset.field][1]=el.value)}
async function startRecording(){try{const stream=await navigator.mediaDevices.getUserMedia({audio:true});chunks=[];recorder=new MediaRecorder(stream);recorder.ondataavailable=e=>e.data.size&&chunks.push(e.data);recorder.start();state.recording=true;state.seconds=0;recordTimer=setInterval(()=>{state.seconds++;document.querySelector('.timer')&&(document.querySelector('.timer').textContent=fmt(state.seconds))},1000);render()}catch{toast('Não foi possível acessar o microfone. Verifique a permissão do navegador.')}}
function stopRecording(){clearInterval(recordTimer);state.recording=false;if(recorder&&recorder.state!=='inactive'){recorder.onstop=()=>{audioBlob=new Blob(chunks,{type:recorder.mimeType});recorder.stream.getTracks().forEach(t=>t.stop())};recorder.stop()}go('processing');setTimeout(()=>{document.querySelector('#stageText')&&(document.querySelector('#stageText').textContent='Estruturando dados…')},1000);setTimeout(()=>{state.draft={tipo:'Diário de obra',transcricao:'Hoje avançamos na alvenaria do segundo pavimento. A equipe concluiu a parede leste e solicitou reposição de blocos para amanhã.',campos:[['Etapa','Alvenaria'],['Serviço','Parede leste do 2º pavimento'],['Equipe','6 profissionais'],['Próxima ação','Repor blocos amanhã']]};go('review')},2200)}
function action(a){if(a==='back'){if(state.screen==='obra')go('home');else if(state.screen==='detail')go('obra');else if(state.screen==='recording'){clearInterval(recordTimer);recorder?.stream?.getTracks().forEach(t=>t.stop());state.recording=false;go('obra')}else if(state.screen==='review')go('obra')}if(a==='record')go('recording');if(a==='toggle-record')state.recording?stopRecording():startRecording();if(a==='discard'){state.draft=null;go('obra')}if(a==='submit'){obra().registros.unshift({id:'r'+Date.now(),tipo:state.draft.tipo,status:'quarentena',duracao:Math.max(state.seconds,1),data:'Agora',transcricao:state.draft.transcricao,campos:state.draft.campos});save();state.draft=null;go('obra');toast('Registro enviado para aprovação.')}if(a==='play'){const r=registro();state.playing=!state.playing;clearInterval(playTimer);if(state.playing){playTimer=setInterval(()=>{state.play+=100/(r.duracao*10);if(state.play>=100){state.play=0;state.playing=false;clearInterval(playTimer)}render()},100)}render()}}
window.addEventListener('online',()=>{toast('Conexão restabelecida.');render()});window.addEventListener('offline',()=>{toast('Modo offline ativado.');render()});
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js'));
render();
